# Generated by TestFlowAssistant

```gherkin
Feature: Checkout Payment Regression — Authorization Accuracy, Stock Consistency, and Duplicate-Charge Prevention
  As an e-commerce customer
  I want my checkout payment to be authorized and captured accurately and safely
  So that I am charged the correct amount, only for items that remain in stock, without duplicate debits

  Background:
    Given the customer has items in the shopping cart
    And the payment gateway sandbox environment is available

  @smoke @critical @risk-critical
  Scenario: Authorized amount matches cart subtotal after a valid promo code discount
    Given the cart subtotal is a known value
    And a valid, unexpired promo code is applied to the cart
    When the customer submits payment for authorization
    Then the authorized amount equals the cart subtotal minus the promo discount
    And the order status reflects "authorized"

  @regression @risk-critical
  Scenario: Capture is blocked when an item becomes unavailable before capture
    Given an item in the cart has been authorized for payment
    When the item's stock is depleted before payment capture
    Then the payment capture is blocked
    And the order status is "unavailable" and not "confirmed"

  @negative @risk-high
  Scenario: Retry after a payment timeout does not create a duplicate authorization
    Given a payment authorization request times out mid-transaction
    When the customer retries the same payment using the original idempotency key
    Then only one authorization record exists for the order
    And no duplicate debit occurs

  @regression @data-driven @risk-critical
  Scenario Outline: Promo code category determines the authorized amount
    Given the cart subtotal is a known value
    And the customer applies a promo code of type "<promo_code_type>"
    When the customer submits payment for authorization
    Then the authorized amount is "<expected_result>"

    Examples:
      | promo_code_type   | expected_result                                   |
      | valid-active       | subtotal minus discount                           |
      | expired             | subtotal unchanged, promo rejected                |
      | stacked-duplicate   | subtotal unchanged beyond single applied discount — stacking rule TBD, see Blockers |

  @boundary @edge-case @risk-critical
  Scenario: Authorized amount at the full-discount boundary is handled per gateway rule
    Given a promo discount equal to the full cart subtotal value is applied
    When the customer submits payment for authorization
    Then the authorized amount does not fall below the payment gateway's minimum payable amount
    And the order status reflects either "authorized" or "rejected" consistent with that minimum-amount rule

  @security @risk-high
  Scenario: Card CVV and full PAN are not exposed after a declined transaction
    Given the customer submits payment using a sandbox test card configured to be declined
    When the transaction is declined
    Then the error message shown to the customer contains no CVV value and no full PAN
    And the application logs contain no CVV value and no full PAN
    And any card reference displayed shows only the first six and last four digits

  @security @negative @risk-high
  Scenario: Promo code field rejects an injection pattern and the authorized amount is unchanged
    Given the cart subtotal is a known value before promo code entry
    When the customer submits a SQL or script injection pattern in the promo code field
    Then the promo code is rejected
    And the authorized amount remains equal to the original cart subtotal
    And the resulting error message reveals no internal system detail
```

---

## Traceability & notes

| Scenario | Risk covered | Band source |
|---|---|---|
| Authorized amount matches cart subtotal | R-01 | critical (20) |
| Capture blocked on stock depletion | R-02 | critical (20) |
| Retry after timeout / idempotency | R-03 | high (15) |
| Promo code category outline | R-01 | critical (20) |
| Full-discount boundary | R-01 (boundary condition) | critical (20) |
| CVV/PAN not exposed on decline | R-04 | high (15) |
| Injection pattern in promo field | R-05 | high (12) |

**Open items carried from the plan (not resolved here, flagged not fabricated):**
- Stacked/duplicate promo code business rule is **TBD** per the plan's Blockers section — the outline's `stacked-duplicate` row describes expected behavior qualitatively rather than asserting a specific rule.
- The payment gateway's exact minimum payable amount is **not specified** in the test basis — the boundary scenario asserts the relationship (not-below-minimum) rather than a numeric value.
- No scenario numbers, amounts, or card data are drawn from real values; sandbox/test data only, per domain guidance.

This draft requires tester review before execution; risk tags reflect the Approved Risk Register bands as supplied.