# Generated by TestFlowAssistant

Feature: Checkout Payment Regression — Card Payment, Promo Code, and Stock Validation
  As an E-commerce Customer
  I want my card payment, promo discount, and stock availability to be validated accurately at checkout
  So that I am charged the correct amount exactly once, my order status reflects the true payment outcome, and my card data is never exposed

  Background:
    Given the customer has a cart validated for current stock and price
    And the customer is on the checkout page using sandbox test payment credentials

  @smoke @critical @risk-critical
  Scenario: Order is confirmed only when gateway authorization is approved
    Given the customer submits payment for the cart total
    When the payment gateway returns an approved authorization response
    Then the order status is set to "Confirmed"
    And exactly one charge record is created for the authorized amount

  @negative @regression @risk-critical
  Scenario Outline: Order is not created when gateway authorization does not succeed
    Given the customer submits payment for the cart total
    When the payment gateway returns a "<gateway_response>"
    Then no order is created
    And the customer sees a "<expected_status>"

    Examples:
      | gateway_response  | expected_status                  |
      | declined response | generic payment declined message |
      | timeout           | generic payment timeout message  |

  @regression @risk-high
  Scenario: Payment authorization is reversed when stock is depleted before capture
    Given the customer's payment has been authorized for a cart item that is currently in stock
    When that item's stock becomes zero before the capture step executes
    Then the payment authorization is reversed
    And the customer sees a message that the item is no longer available

  @boundary @edge-case @regression @risk-high
  Scenario: Captured amount reflects the final recalculated total when a promo discount equals the cart subtotal
    Given the customer applies a promo code whose discount equals the cart subtotal
    When checkout proceeds to the capture step
    Then the amount submitted for capture equals the recalculated cart total of zero
    And the capture step does not submit a negative amount to the payment gateway

  @regression @risk-high
  Scenario: Retrying a timed-out payment with the same idempotency key does not create a duplicate charge
    Given the customer submits payment for the cart total using a unique idempotency key
    When the payment request times out and the customer retries with the same idempotency key
    Then exactly one charge is created for the cart total
    And exactly one order is created

  @security @risk-medium
  Scenario: Card number and CVV are never exposed after a completed payment
    Given the customer completes a card payment
    When the API response, UI error state, and application logs are inspected
    Then the card number is displayed only as masked first6/last4
    And the CVV value is never present in the response or log output

  @security @regression @data-driven @risk-medium
  Scenario Outline: Promo code field rejects oversized and injection-pattern input
    Given the customer enters a "<promo_input>" into the promo code field
    When the customer submits the promo code
    Then the system returns a "<expected_response>"
    And no backend stack trace or internal error detail is exposed

    Examples:
      | promo_input                                  | expected_response          |
      | string exceeding the field's maximum length  | generic invalid-code error |
      | SQL injection pattern (' OR '1'='1)          | generic invalid-code error |
      | script injection pattern (<script>alert(1)</script>) | generic invalid-code error |

---

**Coverage notes (for tester review):**
- R-01 covered by scenarios 1–2 (positive/negative state-transition pair on order confirmation).
- R-02 covered by scenario 3 (stock re-validation at capture, EP: valid-stock vs. depleted-stock).
- R-03 covered by scenario 4 (boundary: discount = subtotal, capture amount floor at zero).
- R-04 covered by scenario 5 (reliability — idempotency key retry).
- R-05 covered by scenario 6 (security — data masking, no negative-path duplication needed since it's a single verification condition).
- R-06 covered by scenario 7 (security — EP/BVA on promo input: oversized length, SQL injection, script injection).
- Quality gate check: ≥1 negative scenario ✔ (scenario 2), ≥1 boundary/edge-case ✔ (scenario 4), ≥1 security scenario ✔ (scenarios 6–7).

**Open items carried from the plan, not resolved here:**
- 3D Secure/OTP step inclusion — TBD, not specified. If confirmed in scope, an additional scenario will be needed.
- Promo code stacking rules — not specified; scenario 4 assumes a single promo code only.
- Exact maximum accepted length for the promo code field — not specified in the test basis; scenario 7 references "the field's maximum length" without an invented figure.

This draft is for tester review — it is not an approved or authoritative artifact until you sign off on it.