# Generated by TestFlowAssistant — Stage: Scenarios

```gherkin
Feature: Checkout Payment Amount Integrity and Lifecycle Consistency
  As an E-commerce Customer
  I want the amount charged at checkout to match the price I am shown and the order status to reflect the true payment outcome
  So that I can trust the checkout process and am never charged incorrectly or left with a mismatched order state

  Background:
    Given the customer has an active authenticated checkout session
    And the customer has items in the cart eligible for promo code and stock validation

  @smoke @critical @risk-critical
  Scenario: Gateway authorization amount matches the displayed cart total after promo and stock recalculation
    Given the customer applies a valid promo code to the cart
    And the cart subtotal is recalculated after a stock adjustment
    When the customer proceeds to payment authorization
    Then the gateway authorization amount equals the cart total displayed to the customer to the cent
    And no discrepancy between displayed total and authorized amount is recorded

  @regression @risk-critical
  Scenario: Order and payment state remain consistent when stock depletes during the payment authorization window
    Given the customer has initiated payment authorization for an item with limited stock
    When the item's stock is depleted by another transaction before authorization completes
    Then the payment remains authorized and not captured
    And the stock hold for the item is released
    And the order status reflects a pending-fulfillment-review state rather than confirmed

  @regression @data-driven @risk-high
  Scenario Outline: Gateway callback status correctly updates the order lifecycle state
    Given an order has an authorized payment awaiting a gateway callback
    When the payment gateway sends a callback with status "<callback_status>"
    Then the order lifecycle state updates to "<expected_order_state>"

    Examples:
      | callback_status | expected_order_state |
      | success          | confirmed             |
      | failure          | payment_failed        |
      | timeout          | pending_retry         |

  @security @risk-high
  Scenario: Error response masks card data to first6/last4 only
    Given the customer submits a card payment that results in a gateway decline
    When the checkout service returns the error response to the customer
    Then the response displays only the first six and last four digits of the card number
    And no CVV value appears in the response body
    And the application log for this transaction contains no full card number or CVV

  @negative @security @risk-high
  Scenario: Expired session token is rejected when reused at checkout
    Given the customer's checkout session token has expired due to inactivity
    When the customer attempts to submit a payment using the expired token
    Then the checkout service rejects the request with an authentication error
    And no payment authorization is created for the rejected request

  @regression @risk-medium
  Scenario: Recalculated price after a cart change matches both the UI display and the captured payment amount
    Given the customer has applied a promo code to the cart
    When an item in the cart becomes unavailable and the cart total is recalculated
    Then the UI displays the recalculated total
    And the amount captured by the payment gateway equals the recalculated total displayed

  @boundary @edge-case @risk-critical
  Scenario: Minimum chargeable amount after maximum promo discount is accepted by the gateway
    Given a promo code reduces the cart total to the smallest chargeable currency unit
    When the customer submits payment for this minimum amount
    Then the gateway authorization succeeds for the minimum chargeable amount
    And the order total displayed matches the amount authorized
```

---

**Traceability notes (for tester review):**
- Scenario 1 → R-01 (critical) — amount-integrity assertion on the promo+stock recalculation path.
- Scenario 2 → R-02 (critical) — stock/payment race condition state consistency.
- Scenario 3 (outline) → R-04 (high) — callback-driven order lifecycle transitions; three representative callback statuses selected by equivalence partitioning (success / failure / timeout), not exhaustively.
- Scenario 4 → R-03 (high) — security/data-exposure condition (masked card data).
- Scenario 5 → R-03 (high) — security/negative condition (expired token reuse); kept separate from Scenario 4 since it is a distinct test condition (session validity vs. data masking).
- Scenario 6 → R-05 (medium) — recalculation-consistency condition.
- Scenario 7 → R-01 (critical) — boundary value analysis at the minimum chargeable amount, distinct from Scenario 1's mid-range recalculation condition.

**Open items carried from the Test Plan (not resolved here, per Blockers/Dependencies):**
- Promo validation location (client/server) — affects whether a tamper-input security scenario should be added later; marked TBD.
- Sandbox gateway credentials/test cards availability — required before these scenarios can move to Cases/Automate stages.
- Stock validation timing model (pre-auth hold vs. post-capture) — Scenario 2's exact state names (e.g., "pending fulfillment review") are illustrative pending this confirmation and should be revised once the actual state model is confirmed.

This is a draft artifact for tester review; no scenario here is approved or authorized for execution until a human reviewer signs off.