A few transparency notes before the artifact:

- **Risk tags**: No risk register (Test Plan artifact) was supplied in this session, so per the fallback rule ("a scenario covering no listed risk is @risk-medium") every scenario below is tagged `@risk-medium`. Adjust these once a risk register with R-xx rows exists.
- **Scope**: Limited strictly to `/login` — valid sign-in, invalid password, unknown email, and empty-form validation, per your stated scope. No registration/reset scenarios are included, as none exist.
- **Security scenario**: The no-enumeration outline scenario is tagged `@security` since it verifies the security requirement that wrong-password and unknown-email cases are indistinguishable (ISO 25010 security characteristic).
- **Design techniques applied**: equivalence partitioning (valid vs. invalid credential class), boundary value analysis (empty vs. whitespace-only input), one test condition per scenario.

```gherkin
# Generated by TestFlowAssistant

Feature: Sign-in
  As a registered TestFlowAssistant user
  I want to sign in with my email and password
  So that I can reach my authenticated dashboard

  Background:
    Given I am on the TestFlowAssistant sign-in page
    And I am not currently signed in

  @smoke @critical @risk-medium
  Scenario: Successful sign-in with valid credentials
    Given I have a registered email and its matching password
    When I submit the sign-in form with those credentials
    Then the dashboard is displayed
    And the "new-session-btn" control is visible

  @negative @security @risk-medium
  Scenario Outline: Invalid credentials are rejected without revealing which field was wrong
    Given I am on the sign-in page
    When I submit the sign-in form with a "<credential type>" combination
    Then the error message "Invalid email or password." is displayed
    And I remain on the sign-in page

    Examples:
      | credential type                          |
      | registered email with an incorrect password |
      | email not registered in the system         |

  @negative @risk-medium
  Scenario: Empty-form submission is blocked with inline validation
    Given I am on the sign-in page
    When I submit the sign-in form with both the email and password fields empty
    Then inline validation errors are displayed for the required fields
    And I remain on the sign-in page

  @boundary @edge-case @risk-medium
  Scenario: Whitespace-only input is treated as empty
    Given I am on the sign-in page
    When I submit the sign-in form with whitespace-only values in the email and password fields
    Then inline validation errors are displayed for the required fields
    And I remain on the sign-in page
```

This draft is ready for your review — please confirm the risk-tag assumption and the credential-type wording in the outline before this moves to the Cases stage.