import { defineConfig, devices } from '@playwright/test';

/**
 * Generated by TestFlowAssistant. Safe to edit — republishing overwrites it.
 *
 * Deliberately starts no web server: the application under test lives elsewhere
 * and is named by APP_URL. A config that boots something is a config that can
 * collide with whatever is already listening.
 */
export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: process.env.PLAYWRIGHT_JSON_OUTPUT_NAME ? 'json' : 'list',
  use: {
    baseURL: process.env.APP_URL,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
});
